### ISSUE TITLE
README IMCOMPREHENSIVE

### ISSUE THREAD

**Issue by andela-iokonkwo** [andela-oosiname/bonvoyage#21]
Your solution didn't contain adequate documentation in the README. 

From the Rubric, in order to meet expectations; the following questions must be  answered.

- How can I get started with the application?
- What are the  external dependencies of the project?
- How do I  run the tests?
- What are the features of the application?
- What are the limitations of the application?

**Comment by andela-oosiname** [comment]
I am currently writing the README, I have started the chore on pivotal tracker. It would definitely be ready before the defence on Wednesday.

**Comment by andela-iokonkwo** [comment]
Alright. :+1:
